// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykkicwhdkdlygmhqjloc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlra2ljd2hka2RseWdtaHFqbG9jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMzE5ODAsImV4cCI6MjA2MTkwNzk4MH0.MBLUeJIkBJKjFFCvxF0_PUClPC0pyHAUA8a_aOwSpeI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);